export const data = [
    {
        id: 1,
        role: "Senior",
        title: "Senior Frontend Developer",
        company: "Photosnap",
        level: "Senior",
        posted: "1d ago",
        type: ".Full Time",
        location: ".USA only",
        logos: "photosnap.svg",
        frontend: "Frontend",
        senior: "Senior",
        html: "HTML",
        css: "CSS",
        javascript: "JAVASCRIPT",
        new: "NEW!",
        feature: "FEATURED"

    },
    {
        id: 2,
        role: "Fullstack",
        title: "Fullstack Developer",
        company: "Manage",
        level: "Midweight",
        location: ".Remote",
        posted: "1d ago",
        type: ".Part Time",
        logos: "manage.svg",
        new: "NEW!",
        fullstack: "Fullstack",
        midweight: "Midweight",
        python: "Python",
        react: "React",
        feature: "FEATURED"
    },
    {
        id: 3,
        role: "Frontend",
        title: "Junior Frontend Developer",
        company: "Account",
        level: "Junior",
        location: ".USA only",
        posted: "2d ago",
        type: ".Part Time",
        logos: "account.svg",
        new: "NEW!",
        frontend: "Frontend",
        junior: "Junior",
        react: "React",
        saas: "Saas",
        javascript: "JAVASCRIPT",
    },
    {
        id: 4,
        role: "Frontend",
        title: "Junior Frontend Developer",
        company: "My Home",
        level: "Junior",
        location: ".USA only",
        posted: "5d ago",
        type: ".Contract",
        logos: "myhome.svg",
        frontend: "Frontend",
        junior: "Junior",
        css: "Css",
        javascript: "JAVASCRIPT",
    },
    {
        id: 5,
        role: "Fullstack",
        title: "Fullstack Developer",
        company: "Loop Studio",
        level: "Midweight",
        location: ".Worldwide",
        posted: "1w ago",
        type: ".Full Time",
        logos: "loopstudios.svg", 
        fullstack: "Fullstack",
        midweight: "Midweight",
        javascript: "JAVASCRIPT",
        saas: "Saas",
        ruby: "Ruby",
    },
    {
        id: 6,
        role: "Backend",
        title: "Junior Backend Developer",
        company: "Faceit",
        level: "Junior",
        location: ".USA only",
        posted: "2w ago",
        type: ".Full Time",
        logos: "faceit.svg",
        backend: "Backend",
        junior: "Junior",
        ruby: "Ruby",
        ror: "RoR",
    },
    {
        id: 7,
        role: "Frontend",
        title: "Junior Developer",
        company: "Shortly",
        level: "Junior",
        location: ".Worldwide",
        posted: "2w ago",
        type: ".Full Time",
        logos: "shortly.svg",
        frontend: "Frontend",
        junior: "Junior",
        html: "HTML",
        saas: "Saas",
        javascript: "JAVASCRIPT",
    },
    {
        id: 8,
        role: "Backend",
        title: "Backend Developer",
        company: "Insure",
        level: "Junior",
        location: ".USA only",
        posted: "2w ago",
        type: ".Full Time",
        logos: "insure.svg",
        frontend: "Frontend",
        junior: "Junior",
        vue: "Vue",
        javascript: "JAVASCRIPT",
        saas: "Saas",
    },
    {
        id: 9,
        role: "Fullstack",
        title: "Fullstack Engineer",
        company: "EyecamCo",
        level: "Midweight",
        location: ".Worldwide",
        posted: "3w ago",
        type: ".Full Time",
        logos: "eyecamco.svg",
        fullstack: "Fullstack",
        midweight: "Midweight",
        javascript: "JAVASCRIPT",
        django: "Django",
        python: "Python"
    },
    {
        id: 10,
         role: "Senior",
        title: "Senior Frontend Developer",
        company: "The Air Filter Company",
        level: "Junior",
        location: ".Worldwide",
        posted: "1m ago",
        type: ".Part Time",
        logos: "theairfiltercompany.svg",
        frontend: "Frontend",
        junior: "Junior",
        react: "React",
        saas: "SaaS",
        javascript: "Javascript",
    }
];